all:
	g++ -o npz2nnet npz2nnet.cc -I$(HOME)/tools/cnpy/include -L$(HOME)/tools/cnpy/lib -lcnpy -lz --std=c++11
	g++ -o npz2nnet_pt npz2nnet_pt.cc -I$(HOME)/tools/cnpy/include -L$(HOME)/tools/cnpy/lib -lcnpy -lz --std=c++11
